#!/bin/bash

BIN=/usr/local/bin
iam=$(basename -- "$0")
echo $iam
$BIN/commit "$iam start"

TARGET="*.jpeg"

if [ "$1" != "" ]; then
	TARGET=$1
fi

for f in $TARGET; do
convert "$f" "$(basename "$f" .jpeg)".pdf;
done
rm *.jpeg 2>/dev/null

chmod -R 777 *
$BIN/commit "$iam end"