#!/bin/bash

BIN=/usr/local/bin
iam=$(basename -- "$0")
echo $iam
$BIN/commit "$iam start"

TARGET="*.pdf"
DENSITY=200
QUALITY=90


if [ "$1" != "" ]; then
	TARGET=$1
fi
if [ "$2" != "" ]; then
	DENSITY=$2
fi
if [ "$3" != "" ]; then
	QUALITY=$3
fi

for f in $TARGET; do
convert -units PixelsPerInch -density $DENSITY -quality $QUALITY -colorspace sRGB "$f" "$(basename "$f" .pdf)".jpg;
done
rm *.pdf 2>/dev/null

chmod -R 777 *
$BIN/commit "$iam end"

