#!/bin/bash

BIN=/usr/local/bin
iam=$(basename -- "$0")
echo $iam
$BIN/commit "$iam start"

TARGET="*.pdf"

if [ "$1" != "" ]; then
	TARGET=$1
fi

for f in $TARGET; do
pdftk "$f" burst;
rm "$f" 2>/dev/null;
done
rm "doc_data.txt" 2>/dev/null;

chmod -R 777 *
$BIN/commit "$iam end"
