#!/bin/bash

TARGET="*.pdf"
DENSITY=200
QUALITY=90

CPATH=${PWD}
BIN=/usr/local/bin

if [ "$1" != "" ]; then
	TARGET=$1
fi
if [ "$2" != "" ]; then
	DENSITY=$2
fi
if [ "$3" != "" ]; then
	QUALITY=$3
fi

for f in $TARGET; do
	TMP=$(mktemp -d ./tmp.XXXXXXXXX)
	chmod -R 777 *
	mv "$f" "$TMP/$(basename "$f")" 2>/dev/null
	cd $TMP
	bash $BIN/pdf-split
	for a in *.pdf; do
		convert -units PixelsPerInch -density $DENSITY -quality $QUALITY -colorspace sRGB "$a" "$a"
	done
	pdftk *.pdf cat output "$(basename "$f")"
	mv "$(basename "$f")" ../ 2>/dev/null
	rm *.pdf 2>/dev/null
	cd ..
	rm -R $TMP/ 2>/dev/null
done

chmod -R 777 *
cd $CPATH
