#!/bin/bash

BIN=/usr/local/bin
iam=$(basename -- "$0")
echo $iam
$BIN/commit "$iam start"

TARGET="*.png"
ANGLE=90
DENSITY=200
QUALITY=90


if [ "$1" != "" ]; then
	TARGET=$1
fi
if [ "$2" != "" ]; then
	ANGLE=$2
fi
if [ "$3" != "" ]; then
	DENSITY=$3
fi
if [ "$4" != "" ]; then
	QUALITY=$4
fi

for f in $TARGET; do
convert -units PixelsPerInch -density $DENSITY -quality $QUALITY -colorspace sRGB "$f" -rotate "$ANGLE" "$f" ;
done

chmod -R 777 *
$BIN/commit "$iam end"