#!/bin/bash

BIN=/usr/local/bin
iam=$(basename -- "$0")
echo $iam
$BIN/commit "$iam start"

TARGET="*.png"

if [ "$1" != "" ]; then
	TARGET=$1
fi

for f in $TARGET; do
convert "$f" "$(basename "$f" .png)".jpeg;
done
rm *.png 2>/dev/null

chmod -R 777 *
echo $iam
$BIN/commit "$iam end"