#!/bin/bash

TARGET="*.xls"
MODE="landscape"
DENSITY=200
QUALITY=90

CPATH=${PWD}
BIN=/usr/local/bin

if [ "$1" != "" ]; then
	TARGET=$1
fi
if [ "$2" != "" ]; then
	MODE=$2
fi
if [ "$3" != "" ]; then
	DENSITY=$3
fi
if [ "$4" != "" ]; then
	QUALITY=$4
fi

TMP=$(mktemp -d ./tmp.XXXXXXXXX)
mv $TARGET $TMP 2>/dev/null
cd $TMP

bash $BIN/xls-to-pdf $TARGET $MODE
rm $TARGET 2>/dev/null

for f in *.pdf; do
	convert -units PixelsPerInch -density $DENSITY -quality $QUALITY -colorspace sRGB "$f" "$(basename "$f" .pdf)".png;
done
rm *.pdf 2>/dev/null

cd ..
mv $TMP/* ./ 2>/dev/null
rm -R $TMP/ 2>/dev/null

rm $TARGET 2>/dev/null

chmod -R 777 *
cd $CPATH

