#!/bin/bash

BIN=/usr/local/bin
iam=$(basename -- "$0")
echo $iam
$BIN/commit "$iam start"

TARGET="*.xls"

if [ "$1" != "" ]; then
	TARGET=$1
fi

libreoffice6.3 --headless --convert-to xlsx $TARGET
rm $TARGET 2>/dev/null

chmod -R 777 *

$BIN/commit "$iam end"