#!/bin/bash

TARGET="*.xls"

CPATH=${PWD}
BIN=/usr/local/bin

if [ "$1" != "" ]; then
	TARGET=$1
fi

libreoffice6.2 --headless --convert-to xlsx $TARGET
rm $TARGET 2>/dev/null

chmod -R 777 *
cd $CPATH