#!/bin/bash

TARGET="*.xls"
MODE="landscape"

CPATH=${PWD}
BIN=/usr/local/bin

if [ "$1" != "" ]; then
	TARGET=$1
fi
if [ "$2" != "" ]; then
	MODE=$2
fi

if [ $MODE = "landscape" ]
then
    bash $BIN/xls-to-landscape $TARGET
else
    bash $BIN/xls-to-portrait $TARGET
fi

libreoffice6.2 --headless --convert-to pdf $TARGET
rm $TARGET 2>/dev/null

chmod -R 777 *
cd $CPATH