#!/bin/bash

BIN=/usr/local/bin
iam=$(basename -- "$0")
echo $iam
$BIN/commit "$iam start"

TARGET="*.xlsx"

CPATH=${PWD}


if [ "$1" != "" ]; then
	TARGET=$1
fi

libreoffice6.3 --headless --convert-to xls $TARGET
rm $TARGET 2>/dev/null

chmod -R 777 *
cd $CPATH

$BIN/commit "$iam end"